# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-16 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_add_urlField'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='duracion',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='enlace',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='fecha_pub',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha publicacion'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'pdf'), (1, 'video')], default=0),
        ),
    ]
