# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 13:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0006_add_usuario_Post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fecha_escrito',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 21, 13, 28, 24, 261054, tzinfo=utc), verbose_name='escrito el día'),
            preserve_default=False,
        ),
    ]
