# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 08:15
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos', '0007_add_fecha_Post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('fecha_escrito', models.DateTimeField(auto_now_add=True, verbose_name='escrito el día')),
                ('respuestas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Comentario')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tagvid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=500)),
                ('enlace', models.URLField(unique=True)),
                ('fecha_pub', models.DateTimeField(auto_now_add=True, verbose_name='fecha publicacion')),
                ('duracion', models.TimeField()),
                ('visualizaciones', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='foro',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='post',
            name='foro',
        ),
        migrations.RemoveField(
            model_name='post',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Foro',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Recurso',
        ),
        migrations.AddField(
            model_name='tagvid',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Video'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Video'),
        ),
    ]
